### ISSUE TITLE
Excel file format cannot be determined, you must specify an engine manually

### ISSUE THREAD

**Issue by pputnik** [Wolverator/CatSystem2-Simple-Translating-Tools#3]
"1) unpack.bat" generates the following error:

```
After copying all files into this folder press Enter...

Copying files into 'extracted' folder and unpacking 'int'-archives may take up to 1 minute per file...
Copying scene.int...
Copying config.int...
Copying update00.int...
Copying cs2.exe...
Processing scene.int...
scene.int: using v_code "AMN-018INN67"
Processing config.int...
config.int: using v_code "AMN-018INN67"
Processing update00.int...
update00.int: using v_code "AMN-018INN67"
Sorting extracted files...
ERROR - Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\NEKOPARA Vol. 3\tools\unpack.py", line 439, in <module>
    sort_resulting_files()
  File "C:\Program Files (x86)\Steam\steamapps\common\NEKOPARA Vol. 3\tools\unpack.py", line 374, in sort_resulting_files
    xlsx_file = pandas.ExcelFile(nametable_xlsx)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_base.py", line 1500, in __init__
    raise ValueError(
ValueError: Excel file format cannot be determined, you must specify an engine manually.

Removing temporary files...
Done! Program will be closed now.
Press any key to continue . . .
```

NekoPara vol.3 from Steam, ver 1.0
cs2.exe ver 2.6.1.76

pandas 2.0.2
XlsxWriter 3.1.2

Could you help, please?

**Comment by pputnik** [comment]
Well, this can help, but I'm unsure because I faced another error. But just in case:
xlsx_file = pandas.ExcelFile(nametable_xlsx, engine='xlrd')

**Comment by pputnik** [comment]
My apologies, I'm still unsure if it's the same error, but at least it's related. 

The next error is:

```
update00.int: using v_code "AMN-018INN67"
Sorting extracted files...
ERROR - Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\NEKOPARA Vol. 3\tools\unpack.py", line 440, in <module>
    sort_resulting_files()
  File "C:\Program Files (x86)\Steam\steamapps\common\NEKOPARA Vol. 3\tools\unpack.py", line 375, in sort_resulting_files
    xlsx_file = pandas.ExcelFile(nametable_xlsx, engine='xlrd')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_base.py", line 1513, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_xlrd.py", line 35, in __init__
    super().__init__(filepath_or_buffer, storage_options=storage_options)
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_base.py", line 540, in __init__
    self.book = self.load_workbook(self.handles.handle)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_xlrd.py", line 48, in load_workbook
    return open_workbook(file_contents=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlrd\__init__.py", line 166, in open_workbook
    file_format = inspect_format(filename, file_contents)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlrd\__init__.py", line 59, in inspect_format
    path = os.path.expanduser(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 321, in expanduser
TypeError: expected str, bytes or os.PathLike object, not NoneType

Removing temporary files...
Done! Program will be closed now.
Press any key to continue . . .
```

**Comment by pputnik** [comment]
Digging more in `...Lib\site-packages\xlrd\__init__.py` I found that in 
`inspect_format(filename, file_contents)`

Value of `filename` is empty (and it's expected because of the previous step `open_workbook(file_contents=data)` but what is more important is that `file_contents` here is empty too:

```
print(f"file_contents={file_contents}") # just before file_format = inspect_format(filename, file_contents)
file_contents=b''

```

**Comment by pputnik** [comment]
Solution is here: https://stackoverflow.com/a/76119258/1013183
The save() method has been deprecated and removed in Pandas. You should use close() instead.

**Comment by Wolverator** [comment]
I see that it works for me, but i coded that back in 2022, seems like before Pandas update.

I will update my libs and fix this in next few days, thanks for pointing out 👍 

(ideally i'll make Git pack my code and required version of libs into .exe via Git CI or so, i still need to learn how to do that, to make Git pack an .exe from my .py code 😅 )

**Comment by Wolverator** [comment]
Seem to be some problems with different Python or libs versions i can't identify for now...
I have my code work perfectly on my PC, but exact same code fails at friend's PC who has same Python 3.10 and same pandas version...
If you can let me question you about your Python and Pandas versions - please write them here or DM me in Discord `sherekhanromeo`.

Ideally i still want to pack all code into .exe to make it standalone and not requiring installed python and it's modules =\
